# Generated by Django 2.0.2 on 2018-02-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='restuarant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('cuisine', models.CharField(max_length=30)),
                ('walking_time', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('specialties', models.CharField(max_length=100)),
                ('review', models.TextField()),
            ],
            options={
                'db_table': 'restuarant',
            },
        ),
    ]
